useTabs = false
tabWidth = 2
printWidth = 80
endOfLine = "lf"
bracketSameLine = true

overrides = [{ files = ["*.rs"], options = { tabWidth = 4 } }]

plugins = ["prettier-plugin-tailwindcss", "prettier-plugin-rust"]
